apiVersion: 1
datasources:
  - id: 1
    uid: "P8E3CEFD57F085127"
    orgId: 1
    name: "docker-omero-dropbox"
    type: "yesoreyeram-infinity-datasource"
    url: "http://omerodropbox:13000"
    basicAuth: false
    basicAuthUser: ""
    isDefault: true
    jsonData:
      global_queries: []
    readOnly: true
    editable: false
